### ISSUE TITLE
[Feature Request] Settings Menu

### ISSUE THREAD

**Issue by 17hoehbr** [cryptofyre/Apple-Music-Electron#101]
It seems like this application has a lot of customization options such as the window buttons and custom CSS. It would be nice if these could all be modified by the user on the fly without having to recompile the application every time. My version has a settings menu that is accessible by pressing Alt, however most of the settings don't perfectly line up with this repo. I'll mess around with it and see what I can get working. Ideally the following options would be available:

- CSS Menu
- Apple style window buttons toggle (imo should be disabled by default)
- Proxy support
- Dark mode toggle (could also just be included in the CSS Menu)

**Comment by 17hoehbr** [comment]
The settings menu in my original app is pretty barebones and probably wouldn't scale well with the rest of the settings in the config.json file. Something like this however could work nicely: https://github.com/tkambler/electron-preferences

**Comment by child-duckling** [comment]
Working on it now...

![Not polished at all](https://cdn.discordapp.com/attachments/843954531217178634/862457431850221569/unknown.png)
