### ISSUE TITLE
[Feature Request] Streamer Mode

### ISSUE THREAD

**Issue by 17hoehbr** [cryptofyre/Apple-Music-Electron#103]
In my repo I've documented a method for streamers to incorporate their currently playing song in Apple Music via OBS using this app. Essentially all that it really does is take advantage of the window scaling and gives instructions on how to add it into OBS, no actual code is modified. I'll test to make sure it still works in this version and create a pull request into the Wiki if it does.

**Comment by 17hoehbr** [comment]
Apparently I can't create a merge request into the wiki, but I've created the streaming page here: https://github.com/17hoehbr/Apple-Music-Electron-Wiki/blob/master/Streaming.md

**Comment by coredev-uk** [comment]
Streamer mode has been added and can be enabled using the configuration option `streamerMode`. It will be available in the next release.
