### ISSUE TITLE
Unable to "Enable Web Security" per 2.3.0 Release instructions

### ISSUE THREAD

**Issue by carlos-miller-466** [cryptofyre/Apple-Music-Electron#108]
Despite having `config.json` present in `~/.config/Apple\ Music/` and enabling what I perceived to be "Web Security" by setting "allowRunningInsecureContent" to false, I am still unable to login with my Apple ID. The error provided is similar to issue #95, "Apple Music is not available in your country or region."

I have attempted to compile from source instead of using the AppImage provided in the release. Except running `yarn dist` yielded even more errors; none of which related to this issue, rather `electron-builder` struggling to download a dependency.

**Comment by coredev-uk** [comment]
Yeah, it's not that clear. WebSecurity is the disableCORS option. Probably best to leave allowRunningInsecureContent to default (true).
