### ISSUE TITLE
Signed in but only samples play, not the full song.

### ISSUE THREAD

**Issue by georgeawwad** [cryptofyre/Apple-Music-Electron#11]
I'm on Windows 10 (20H2) and I've been looking for an iTunes replacement when I found this repo.
Unfortunately, full songs don't play. I have a subscription for sure. That's not the issue.

Can anyone else confirm Windows 10 build is broken?

**Comment by iiFir3z** [comment]
I myself have been experiencing that bug. Im currently working on resolving it, one current way to get paste the sample bug is to logout completely out of Apple Music then log back in after restarting the application. That should fix the issue.

**Comment by georgeawwad** [comment]
Not quite working for me. But that's okay for now I'm using the official web app.

**Comment by iiFir3z** [comment]
v1.5.6 should have fixed this issue completely as in my testing it did so. Feel free to confirm so I can close this issue.
