### ISSUE TITLE
Error when updating to 2.4.0

### ISSUE THREAD

**Issue by hoodmonalisa** [cryptofyre/Apple-Music-Electron#115]
So, I just tried updating to the new version and after installing it this is the message I get when I try to open it.

![image](https://user-images.githubusercontent.com/76568365/124614549-baed6b80-de4a-11eb-9887-16c11ca4ceab.png)

**Comment by cryptofyre** [comment]
Remove your config.json

**Comment by hoodmonalisa** [comment]
But where can I find it?

**Comment by cryptofyre** [comment]
Documents/Apple Music/config.json

**Comment by hoodmonalisa** [comment]
I removed and nothing changed, still the same message.

**Comment by cryptofyre** [comment]
Hmm. Ill push a new build in a minute.

**Comment by coredev-uk** [comment]
This should now be fixed, and in the next release, you should not get any errors as you go here.
