### ISSUE TITLE
"Apple Music is not available in your country or region"

### ISSUE THREAD

**Issue by Drewza021** [cryptofyre/Apple-Music-Electron#118]
![image](https://user-images.githubusercontent.com/87099504/124835999-91a51a80-dfc5-11eb-9e7a-75e215c6e548.png)

I live in Australia, where it is certainly supported as I have it on my phone, and my family and multiple friends use it.  I don't have a VPN on, and when I tried to log in and I got the authentication notification on my iPad, it displayed the right location.

**Comment by coredev-uk** [comment]
Install the latest beta and enable AuthMode on the configuration file, that should fix it.

**Comment by Drewza021** [comment]
This happened upon installing the beta
![image](https://user-images.githubusercontent.com/87099504/124837678-a8993c00-dfc8-11eb-920c-72787535667f.png)

**Comment by coredev-uk** [comment]
delete config file

**Comment by coredev-uk** [comment]
`Documents/Apple Music
`

**Comment by 0nimaru** [comment]
For anyone else having a similar issue, authMode is in the preferences JSON file found at `%APPDATA%/Roaming/Apple Music/preferences`. Set the value to true. Log in. Jam out. 

If all the text on the sidebar disappears, remove the authMode value true. Restart Apple Music.

**Comment by child-duckling** [comment]
please refer to #155 for updated instructions
