### ISSUE TITLE
Song not available in your country

### ISSUE THREAD

**Issue by wtfcxt** [cryptofyre/Apple-Music-Electron#122]
I've seen many people with the issue that they can't even login to apple music - but my problem is that I can't play any songs.
![grafik](https://user-images.githubusercontent.com/53837207/124986562-09159100-e03c-11eb-9df5-a5fd795f3bff.png)

**Comment by wtfcxt** [comment]
Translation from German:
Article (Song?) not available in your country
Try, switching back to the registered store of this account. (but how?)

**Comment by linusheinz** [comment]
Same problem  also german account

**Comment by perseoGI** [comment]
Same problem here with an Spanish account, please fix this ASAP!

**Comment by coredev-uk** [comment]
Please follow the troubleshooting guide that can be found [here](https://github.com/cryptofyre/Apple-Music-Electron/wiki/Troubleshooting).
