### ISSUE TITLE
Force language does not work or I don't know how to force it

### ISSUE THREAD

**Issue by mysteriously** [cryptofyre/Apple-Music-Electron#127]
Hi,

My Windows language is English, however region (time and date) and input language is Polish. I've tried the following combinations and none of them worked:
"forceApplicationLanguage": "en-US"
"forceApplicationLanguage": "en"
"forceApplicationLanguage": "english"

Without quotes those combinations gives me javascript errors at app startup.

How should I force English?

**Comment by coredev-uk** [comment]
In the next release which included a UI for settings, there is a drop down selector so the language should no longer be a problem.

**Comment by mysteriously** [comment]
Hello,

Upgrading to 2.4.0 beta 3 allowed me to change language. However app settings option is gone from menu after restarting the app to apply the changes

**Comment by coredev-uk** [comment]
This is fixed in the next release

**Comment by mysteriously** [comment]
"Settings Menu can be invoked with CTRL+ALT+S"
Actually by default it is enough to press right ALT + S on Windows to invoke the menu. It also prevents typing the Polish letter "ś".

**Comment by coredev-uk** [comment]
We're adding an option to access the menu through a button in the UI. In here you can set yourself a keybind.

**Comment by coredev-uk** [comment]
Upon the release of v2.4 if any further issues occur feel free to reopen this issue.
