### ISSUE TITLE
Audio playback device resets to default after restarting app

### ISSUE THREAD

**Issue by imIrony** [cryptofyre/Apple-Music-Electron#128]
Steps to recreate:

1. Open sound settings and access app volume and device preferences
2. Change output device for app to a separate device other than default
3. Relaunch app and audio plays through default device

Can be resolved by setting output device to default for app and changing it once again.

Platform: Windows 10
Version: 2.4.0

**Comment by mysteriously** [comment]
Where do you see menu to choose audio device?

**Comment by imIrony** [comment]
This is under the Windows sound settings.
