### ISSUE TITLE
Unable to type in search bar when explorer is terminated

### ISSUE THREAD

**Issue by mysteriously** [cryptofyre/Apple-Music-Electron#131]
Hi,

I use RDP to connect from PC1 to PC2. Windows taskbars are overlapping so I have to terminate explorer.exe on host before connecting to guest. Once I do it I can not use keyboard multimedia keys anymore and type in search bar in the app. I understand that first thing is Windows limitation but I am not sure about the other.

**Comment by child-duckling** [comment]
Those are issues with you RDP client/server. Not on our end
