### ISSUE TITLE
Apple Music is not available in your country or region.

### ISSUE THREAD

**Issue by BreckenLusk** [cryptofyre/Apple-Music-Electron#139]
Upon signing in, I receive an error stating that "Apple Music is not available in your country or region." I live in the United States and my Windows VM language and region settings are set accordingly.

**Comment by coredev-uk** [comment]
Please follow the troubleshooting guide that can be found [here](https://github.com/cryptofyre/Apple-Music-Electron/wiki/Troubleshooting).

**Comment by coredev-uk** [comment]
Duplicate issue. Please see #122, #118, #95 or #88. Try all the troubleshooting comments shown in those and it should fix your issue.

**Comment by child-duckling** [comment]
please refer to #155 for updated instructions
