### ISSUE TITLE
Can't play any music

### ISSUE THREAD

**Issue by space192** [cryptofyre/Apple-Music-Electron#140]
![image](https://user-images.githubusercontent.com/44359684/126479309-7b434b82-e6f7-489e-80f3-4d61cbfa3a33.png)
whenever i try to play some music i get this error message :/ (translated from french : 

This Article is not available in your country
Try to come back to the Store registered on your account)

**Comment by coredev-uk** [comment]
Please see #139, #122, #118 or #88. Try all the troubleshooting comments shown in those and it should fix your issue.

**Comment by space192** [comment]
For me the solution was to change disableCORS from false to true :D
