### ISSUE TITLE
[PROBLEM] Repeat is not working

### ISSUE THREAD

**Issue by devilAPI** [cryptofyre/Apple-Music-Electron#16]
The repeat thing is not working, i dont know if this is on apples side or a problem caused by this repo, or maybe if its apple's side fix it urself by making the song replay

**Comment by iiFir3z** [comment]
I have a possible workaround for this. Unfortunately its on Apple's end however I can make it use the MusicKit API to automatically replay the song if the button is on.

**Comment by devilAPI** [comment]
fixed by apple 🥰
