### ISSUE TITLE
No scrollbar at the side

### ISSUE THREAD

**Issue by kjay7m** [cryptofyre/Apple-Music-Electron#20]
Not able to scroll within the app unless I use the keyboard

**Comment by devilAPI** [comment]
ya i have the same "problem", but its intended and i personally use my scroll wheel so its not a big deal for me

**Comment by devilAPI** [comment]
in the `index.js`, just remove this:

`await win.webContents.insertCSS('::-webkit-scrollbar { display: none; }')`

**Comment by iiFir3z** [comment]
Im going to reskin the scroll bars as they use the default chrome looking ones that look hideous on a dark theme.

**Comment by devilAPI** [comment]
> the default chrome looking ones that look hideous

i totally agree.

What about this one? It looks almost like the Apple iOS one: https://codepen.io/waterplea/pen/dVMopv

**Comment by cryptofyre** [comment]
Made a ton of optional features that you can enable or disable during the compilation process. (default builds have these enabled by default)
![image](https://user-images.githubusercontent.com/33162551/116710065-3253da00-a986-11eb-9efd-2c9bee253e5c.png)
