### ISSUE TITLE
No detection if App has already been opened

### ISSUE THREAD

**Issue by space192** [cryptofyre/Apple-Music-Electron#21]
if you launch the app once then minimize it and then relaunch again it doesn't check if the app is already open and create a second instance
![image](https://user-images.githubusercontent.com/44359684/107981684-d9011f00-6fc2-11eb-98f3-fecae7def326.png)

**Comment by devilAPI** [comment]
Good idea, i had the Problem that i opened 6 instaces cause i completely forgot about the minimize thing.

**Comment by arya1106** [comment]
I implemented the tray icon, I'll look into fixing this

**Comment by Dream-cake** [comment]
This can be fixed with [Electron #appRequestSingleInstanceLock](https://www.electronjs.org/docs/api/app#apprequestsingleinstancelock).

Let me know if u want me to add it.
