### ISSUE TITLE
[Suggestion] Apple Music CSS Themes

### ISSUE THREAD

**Issue by devilAPI** [cryptofyre/Apple-Music-Electron#23]
I was recently looking at [revblaze/AppleMusicUltra](https://github.com/revblaze/AppleMusicUltra) and loved the idea of styling, why not making a new tab under "Radio" called Settings, where you can put a custom css thing, that would be kind of cool, but a huge thing

**Comment by Dream-cake** [comment]
This would only work for a while. Apple is still deving there web app and css etc will change. 

Also this would cause a lot of performance issues. It already has enough of it

**Comment by devilAPI** [comment]
> Apple is still deving there web app
I know, but the CSS is not really changing, and if it is, its not a major change, that can be implemented kind of fast.

> this would cause a lot of performance issues. It already has enough of it
well, there is not a big performance issue, its way more efficient than a Browser, thats it, and changing the CSS is also not a Thing, that would change Performance in any way (if its not a huge theme)

**Comment by cryptofyre** [comment]
CSS Theming is possible in the next update as I have made a directory based stylesheet reader and injector.
