### ISSUE TITLE
[bug] no button at the top of the app (Windows)

### ISSUE THREAD

**Issue by space192** [cryptofyre/Apple-Music-Electron#27]
![image](https://user-images.githubusercontent.com/44359684/111032786-36e02580-840e-11eb-8625-9481548ccdfd.png)

**Comment by devilAPI** [comment]
same problem, here, the js is not "injected", thats why theres an itunes button in the lower left. corner. it's annoying but you can fix it by just reloading the site by clicking on a menu button on the left side.

**Comment by devilAPI** [comment]
fix idea: on the first launch, make the script wait before injecting the code or make it reload (wich is a bad fix)

**Comment by cryptofyre** [comment]
I have since added an await function. This should fix this issue, new builds should be out shortly.

**Comment by cryptofyre** [comment]
Made the custom titlebar optional due to some issues on some platforms. Feel free to uncomment it if you feel the need to use it again.
