### ISSUE TITLE
Apple made a Protection thing i guess

### ISSUE THREAD

**Issue by devilAPI** [cryptofyre/Apple-Music-Electron#28]
It's impossible to play Music now. Everything is blacked out.

**Comment by devilAPI** [comment]
my fault my apple music ran out im such an idiot sorry

**Comment by devilAPI** [comment]
My Apple Music is running out in a week. This is a serious issue.

**Comment by cryptofyre** [comment]
This was just a server back-end issue that has since been resolved. Closing.
