### ISSUE TITLE
No title bar on Ubuntu 20.04 

### ISSUE THREAD

**Issue by a1eaiactaest** [cryptofyre/Apple-Music-Electron#31]
After building with yarn I was kind of confused what to do, so I went to dist directory and installed with `.deb` file. 

Everything works besides that title bar isn't showing up.

![Screenshot from 2021-04-26 14-36-09](https://user-images.githubusercontent.com/55894077/116083347-cda23200-a69c-11eb-94ee-b05951a62fdb.png)

**Comment by a1eaiactaest** [comment]
Oh, i just had to log in. My bad.

**Comment by a1eaiactaest** [comment]
Although it would be nice if it would show up even before logging in.

**Comment by cryptofyre** [comment]
Ill look into it.

**Comment by a1eaiactaest** [comment]
I think I can pull request the [solution](https://github.com/a1eaiactaest/Apple-Music-Electron) to this, although it would delete the custom titlebars, and make them shell default
