### ISSUE TITLE
[Suggestion] Editing the RPC via a config file

### ISSUE THREAD

**Issue by ajunior7** [cryptofyre/Apple-Music-Electron#34]
I would love to have the ability of being able to edit what is being shown. I'm not that big on showing the album name as it can look cluttered depending on the length of the title.

**Comment by cryptofyre** [comment]
Added some configuration options when you compile it! These should be out pretty soon and allow you to customize the app to your liking.

![image](https://user-images.githubusercontent.com/33162551/116709869-f6207980-a985-11eb-8d50-dc5ba0153389.png)
