### ISSUE TITLE
mpris-enabled branch

### ISSUE THREAD

**Issue by vxsl** [cryptofyre/Apple-Music-Electron#37]
> `(NOTE: Mpris is not enabled in this branch. See mpris-enabled)!`

Not sure if you just forgot to publish this branch. I was going to proceed with using Jarek's fork but thought I would check here first as it seems `mpris-enabled` should exist due to #6.

**Comment by cryptofyre** [comment]
Removed the branch temporarily. Should return by 1.6.0

**Comment by JarekToro** [comment]
How is it coming? I'm starting to add more to my build again, but I noticed your repo picking up steam. I figured maybe I could makes some PRs to this repo instead. Do you need assistance integrating Mpris?

**Comment by cryptofyre** [comment]
I shouldn't have an issue adding it myself, but feel free to make a PR cause that would help a lot.
