### ISSUE TITLE
win.setBlur is not a function

### ISSUE THREAD

**Issue by devilAPI** [cryptofyre/Apple-Music-Electron#40]
Shows everytime im opening the app, im on verion 1.5.9 with no settings changed from normal

**Comment by cryptofyre** [comment]
Shit, left a glasstron config option in. Fixing it right now.

**Comment by cryptofyre** [comment]
Alright fixed it, should be good to go now and the precompiled builds are good too.

**Comment by TakaiSaisei** [comment]
@cryptofyre I'm getting the same error with sexytransparencymode = true and the app window is all blank. Is it supposed to be not working at this time?

**Comment by cryptofyre** [comment]
There is a PR I need to approve that makes this option a little easier to use. Please wait for that or look at the commented messages in the code that shows you how to use it.
