### ISSUE TITLE
Apple HiFi Support

### ISSUE THREAD

**Issue by Jonatino** [cryptofyre/Apple-Music-Electron#41]
Apple just announced HiFi music playback with their own ALAC format. Is this something that will be supported on their web app, or only on Apple devices. If the former, having support for this would be fantastic!

https://www.apple.com/newsroom/2021/05/apple-music-announces-spatial-audio-and-lossless-audio/

Thank you for your app, you're doing an amazing job saving the world from having to install iTunes.

**Comment by cryptofyre** [comment]
Thanks for your support! I do plan on manually adding support for HiFi to the app once the full MusicKit is updated and available for me to use.

**Comment by Nosh118** [comment]
As an addition to HiFi support, having options to choose between 256kbps AAC, lossless (16/44.1-24/48) and hi-res lossless (24/88.2-24/192) would be super useful, as well as showing the currently playing sample rate and bit depth.

**Comment by bleomycin** [comment]
Is it documented now what bitrate apple music electron currently streams at?

**Comment by cryptofyre** [comment]
256kbps AAC.

**Comment by Nirzak** [comment]
It's pretty much sad that Apple still has not updated its API.

**Comment by chrisanityyyyy** [comment]
This would be an awesome feature as we, windows users, do not have any support from Apple even thru iTunes at the very least.

**Comment by Nosh118** [comment]
> This would be an awesome feature as we, windows users, do not have any support from Apple even thru iTunes at the very least.

Just to let you know that this won’t be possible until Apple release support for hifi on the web, as this electron app uses Apple’s beta Apple Music website as the core. It is currently available in their private alpha app but hasn’t been pushed to the beta yet. Once that happens then this will be possible.

**Comment by Nirzak** [comment]
> > This would be an awesome feature as we, windows users, do not have any support from Apple even thru iTunes at the very least.
> 
> Just to let you know that this won’t be possible until Apple release support for hifi on the web, as this electron app uses Apple’s beta Apple Music website as the core. It is currently available in their private alpha app but hasn’t been pushed to the beta yet. Once that happens then this will be possible.

More precisely if they update their MusicKit API.

**Comment by mysteriously** [comment]
Someone made lossless audio playback on portable Android player. Not sure uf it will help you but here is the link.
https://www.head-fi.org/threads/astell-kern-a-futura-se200-first-dap-with-multiple-dacs-head-fi-tv.935878/page-64#post-16442828

**Comment by child-duckling** [comment]
Waiting for MusicKit update.

**Comment by chrisanityyyyy** [comment]
Will this ever come in an update or never?

**Comment by cryptofyre** [comment]
Apple is currently implementing this into the Web version and once thats done it will be immediately available in AME.

**Comment by Nirzak** [comment]
> Apple is currently implementing this into the Web version and once thats done it will be immediately available in AME.

Really? Did apple confirm that?

**Comment by cryptofyre** [comment]
I'm friends with a MusicKit/Apple Music Web employee and they confirmed that information to me and they already have it working internally.

**Comment by vapormusic** [comment]
> > Are there any updates on this, or still just waiting?
> 
> Don't know nearly 3 months have been passed and apple even doesn't have started the beta testing process of this feature :(

Nope, no updates from Apple. However things may change soon
