### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by georgeat8** [cryptofyre/Apple-Music-Electron#42]
I see that there are some releases that contain packages that can be installed on Linux systems and some releases that have just a .exe/source code. Is there any way to better support Linux? Maybe through Flatpak (for Ubuntu like systems) or AUR?

**Comment by cryptofyre** [comment]
I previously made packages for Linux and I plan on making more once I get WSL 2 up and running again.

**Comment by cryptofyre** [comment]
As for package repo's I might, but maintaining packages for distros of linux I never use is kind of difficult.

**Comment by georgeat8** [comment]
> As for package repo's I might, but maintaining packages for distros of linux I never use is kind of difficult.

Flatpak might be useful in this case, since it's kind of an universal solution

**Comment by 0neGal** [comment]
The AUR (Arch User Repository) already has a [package for AME](https://aur.archlinux.org/packages/apple-music-electron/), packaged by galross, might wanna add that in the README...

**Comment by cryptofyre** [comment]
> The AUR (Arch User Repository) already has a [package for AME](https://aur.archlinux.org/packages/apple-music-electron/), packaged by galross, might wanna add that in the README...

This looks to be someones elses take on the project which has managed to claim the AUR package. I could however change the name of the package.

**Comment by 17hoehbr** [comment]
I updated the AUR package to point to this repo instead. I've found that Flatpaks are not supported natively by electron-builder and thus can't really be implemented right now, however AppImage's work great. I think between the AUR package, an AppImage release, and a .deb release for each version should suffice.
