### ISSUE TITLE
Cant play any song - Item not available in your country

### ISSUE THREAD

**Issue by Jonatino** [cryptofyre/Apple-Music-Electron#43]
Just downloaded and built the app on linux, but I'm unable to play any of my songs. Playback works on https://music.apple.com.

Screenshot of error:
![https://i.imgur.com/fRxRDc1.png](https://i.imgur.com/fRxRDc1.png)

Error:
```
Item not available in your country
Try switching back to your account's registered storefront
```

My storefront in the app is the same on music.apple.com, Canada (English).

Any ideas as to whats wrong?

**Comment by cryptofyre** [comment]
Try changing your default Apple Music site.

Change

appleMusicUrl = 'https://beta.music.apple.com';

to

appleMusicUrl = 'https://music.apple.com';

In the index.js file.

**Comment by Jonatino** [comment]
It seems like it happens when you select the language through the prompt before you login. I logged out and logged in again without setting my country/language and its working now.

**Comment by cryptofyre** [comment]
Ah well glad you got it resolved.
