### ISSUE TITLE
Last.FM Scrobbling

### ISSUE THREAD

**Issue by decafhotchocolate** [cryptofyre/Apple-Music-Electron#55]
It'd be quite neat to have I think :) I'm assuming it won't be too hard to handle considering the information in Discord Rich Presence is close enough to what is needed for scrobbling (knowing when a track is playing, what that track is, etc.)

**Comment by cryptofyre** [comment]
Does the desktop app scrobbler not do it?
https://www.last.fm/about/trackmymusic

**Comment by decafhotchocolate** [comment]
I've read that it does, at least one the regular client, but I probably should've mentioned I'm on linux. I recognize from another request though that that's not your top priority right now, so shrug.

**Comment by cryptofyre** [comment]
I could likely make a scrobbler module with a config option. Signing in would be a interesting task however.

**Comment by kikandychan** [comment]
the official last.fm scrobbler on windows is not working with Apple Music Electron.
so please try to add native apple music scrobber support. 
as i know the chrome extension web-scrobbler is working with Apple Music Web.

**Comment by cryptofyre** [comment]
Ill see what I can do.

**Comment by cryptofyre** [comment]
Took a while but this feature is now available! https://github.com/cryptofyre/Apple-Music-Electron/releases/tag/v2.4.0 ab61d4a1be2fe384c7cdd41753ad98b9e6d05448

**Comment by tayloroneill** [comment]
The scrobbler does not appear to work for me - wondering if this has to do with the fact that clicking the link on the setup page shows this after clicking allow access (even though it shows a token in the URL). Not sure if this is common or just a me problem.

![lfm](https://user-images.githubusercontent.com/61822772/124609665-2ec35e80-deb3-11eb-8e9a-9bccbc5f4d89.png)

**Comment by cryptofyre** [comment]
The API key being invalid is just the standard no callback error from LastFM's API. I didn't want to setup a callback website so copying the key from the URL is fine.

**Comment by tayloroneill** [comment]
Right true it does seem to use the API key and generate session.json successfully, however I'm not seeing it actually scrobble anything, with dev tools enabled I don't see any requests made to LFM and looking in the log file it appears to log in successfully but not log anything indicating a scrobble attempt at all - neither an error nor success message.

**Comment by cryptofyre** [comment]
I just looked into that and fixed it. Beta 2 should be out shortly.

**Comment by cryptofyre** [comment]
Beta 2 is out and should fix your scrobbling problems.

**Comment by tayloroneill** [comment]
It does function now. Just a few suggestions for improvement -
1. From a fresh install, it initially shows a bunch of error popups the first time LFM logs in.
2. Send the album field as well, right now it just sends the artist and song, which can lead to things being counted under the wrong album if the song is found in multiple albums.
3. Don't scrobble songs immediately, right now they scrobble as soon as they're what's playing. If a song comes on that I decide to skip, it'll scrobble it anyway. Most other software with LFM integration scrobble only if half of the song was listened to.
