### ISSUE TITLE
Song and Cover Art in Discord

### ISSUE THREAD

**Issue by dylbinthedev** [cryptofyre/Apple-Music-Electron#64]
A suggestion:

Better discord integration which shows the played song and album artwork on your discord profile.

**Comment by cryptofyre** [comment]
Album artwork is impossible due to the restrictions of the GameKit SDK by Discord. Spotify has an exclusive API that it uses which includes artwork by URL. As for the played song im not sure what you mean by that.

**Comment by dylbinthedev** [comment]
With played song I meant this: (check attached image.)
So basically, Shows which song your listening too (minus the album art since its not possible.)
![a8a05274b408301681d126c169fc588a](https://user-images.githubusercontent.com/70339581/120075730-c0fd6900-c0a2-11eb-9589-410ad4994a42.png)

**Comment by cryptofyre** [comment]
This already exists.
![image](https://user-images.githubusercontent.com/33162551/120076268-5597a500-c06a-11eb-8590-567e5329f821.png)
