### ISSUE TITLE
Application install triggers Windows Defender

### ISSUE THREAD

**Issue by Lermatroid** [cryptofyre/Apple-Music-Electron#77]
When installing, Windows Defender triggers and warns you about installing the application. I do not know if this is fixable (if it is not, feel free to close the issue) but I though I would make a issue if it is.

**Comment by cryptofyre** [comment]
Unfortunately due to my code signature being so new its gonna do that for awhile. However you can bypass this by installing the certificate on your host machine under your current user.

Download my certificate here:
[Certificate](https://cryptofyre.xyz/cert/cryptofyre.pfx)

**Comment by Lermatroid** [comment]
Thanks, I'll close the issue in a sec. Also, if you don't mind me asking, where is the config file located (I checked the folder in appdata but did not see it)?

**Comment by coredev-uk** [comment]
Configuration can only be done before compiling at the moment. We hope to add a configuration method that can be found in the UI in the future.

**Comment by Lermatroid** [comment]
Ok, thanks!
