### ISSUE TITLE
"Apple Music is not available on your region or country" but it is

### ISSUE THREAD

**Issue by nektwar** [cryptofyre/Apple-Music-Electron#88]
I tried to use your app in my Windows, but when I try to log in with my account I just receive "Apple Music is not available on your region or country" but it is available in my country (Panama). I tried a VPN to the US to see if that would remove the problem, but nope. I've been subscribed for months to Apple Music and I can also use the web version from the browser, but with your app for some reason it won't let me do anything.

![image](https://user-images.githubusercontent.com/9793196/121075595-fe48b180-c79a-11eb-9bca-062f4e43b4a3.png)

**Comment by sg16bbrave** [comment]
Same here. I'm from Panama too.

**Comment by kuzguni** [comment]
I had same promblem. Join discord server and check announcement. I dound solution on there.

**Comment by sg16bbrave** [comment]
> I had same promblem. Join discord server and check announcement. I found solution on there.

Can you please put here the link to the discord server?

**Comment by coredev-uk** [comment]
https://discord.gg/CezHYdXHEM

**Comment by Roddyboii** [comment]
It works but this thing keeps appearing on the bottom.
Also my playlists doesn't show up.

![image](https://user-images.githubusercontent.com/78095397/121835351-9cb7a400-ccc0-11eb-98da-012991f2bc23.png)

**Comment by FernandoMarques-Santos** [comment]
Same problem on the Linux Mint 20 (Brazil). My playlists show but whenever I hit play it pops up a message in Portuguese saying basically "This item is unavailable in your country. Try getting back to the store where your account is registered". My account is registered in Brazil.

**Comment by cryptofyre** [comment]
Apple has fixed this issue and will be patched accordingly to fit the new standard on the development branch. Closing.
