### ISSUE TITLE
Non Availability Issue

### ISSUE THREAD

**Issue by adiavula12** [cryptofyre/Apple-Music-Electron#90]
When I tried to login to my Apple Music account via the electron app, It shows that the service is not available in my region/country. 

I'm from India and I've been using Apple Music for almost a year. It works perfectly fine on my iPhone, Android, Apple Music website and iTunes for windows. But I'm not able to login to my account only via your app. 

Whenever I try to login, after entering my credentials, It just shows the loading symbol for a few seconds and show this prompt saying that the service is not available. 
![image](https://user-images.githubusercontent.com/84370492/121126955-a36c9400-c846-11eb-9b60-16d98bcd4da2.png)

 Please resolve this issue, or please let me know if there is a workaround. I'm really looking forward to trying your app.

**Comment by coredev-uk** [comment]
This is currently an outstanding issue, you can view any updates in #88. This issue will be closed as its a clone.
