### ISSUE TITLE
Option to change between Mac/Windows window buttons (top left vs. top right)

### ISSUE THREAD

**Issue by Nosh118** [cryptofyre/Apple-Music-Electron#94]
It can get pretty confusing when you're maining a windows machine and the close, minimize and maximise buttons are on the left instead of the right. Having the buttons default to each OS' button styles with the option to choose manually would be much appreciated.

**Comment by coredev-uk** [comment]
This is currently an option in the configuration (can be found [here](https://github.com/cryptofyre/Apple-Music-Electron/blob/master/config.json#L12)). If you compile the application you can fix this or you can wait for 2.3.0 and you will be able to edit the configuration yourself, without compiling.

**Comment by cryptofyre** [comment]
that aint quite what they mean't by that. They wanted the macOS window but with the buttons aligned on the right instead of the left.

**Comment by coredev-uk** [comment]
Whoops, shouldn't be too hard to do though.

**Comment by coredev-uk** [comment]
Added to development build, will be available in 2.3.0 and can be enabled with config option macosWindowForceRight.
