### ISSUE TITLE
Showing Apple Music not supported in Country When trying to login

### ISSUE THREAD

**Issue by Adil-MohammedK** [cryptofyre/Apple-Music-Electron#95]
Once the login is done and OTP is passed, it is showing Apple music not showing in the country while it was working few weeks back. The apple music website is working perfectly fine in India. Tried the .exe file and also building from source and tried putting useBeta as false

![image](https://user-images.githubusercontent.com/18614021/123060644-8cbe6380-d428-11eb-9599-e0b8aee7e626.png)

**Comment by shelldandy** [comment]
Reporting same issue on ubuntu 20.04 compiled with beta false locale MX

**Comment by hujiba** [comment]
Also happening to me in the US

**Comment by shelldandy** [comment]
So searching a bit more in the repo the maintainer says we should build on `development` and go from there, trying right now...
https://github.com/cryptofyre/Apple-Music-Electron/issues/88

**Comment by shelldandy** [comment]
Building from the development brands yields an app that won't open on Ubuntu 20.04 installed with dpkg if i do `ps aux` i can see it is indeed running but no window is visible so i proceeded to uninstall it and wait for the next stable release instead :)

**Comment by coredev-uk** [comment]
We are currently working on a patch for the main build, however the issue that you are all getting is happening with CORS, if you try commenting/uncommenting the line and this could fix your issue. Apple is very weird with it as sometimes it wants to work the other times it doesn't.

**Comment by chinook77** [comment]
Same in Argentina.

**Comment by fabian-michael** [comment]
I can login but I can't play any song and it's giving me the same error

**Comment by pb29** [comment]
I got this error too, I'm at South Korea.

**Comment by coredev-uk** [comment]
If you can compile please try and comment the disable CORS line in [index.js](https://github.com/cryptofyre/Apple-Music-Electron/blob/master/index.js#L51). Upon the release of 2.3.0 (which should be soon) you will be able to disable/enable this in the configuration file.

**Comment by pratyush-1327** [comment]
getting same error in india too ...just installed from the latest exe

**Comment by Nosh118** [comment]
Just to let anyone know who doesn’t want to compile themselves, I’m from the UK and had this error and closing it from the taskbar on windows and reopening solved it for me.

**Comment by fabian-michael** [comment]
> Just to let anyone know who doesn’t want to compile themselves, I’m from the UK and had this error and closing it from the taskbar on windows and reopening solved it for me.

This worked for me too

**Comment by pratyush-007** [comment]
> Just to let anyone know who doesn’t want to compile themselves, I’m from the UK and had this error and closing it from the taskbar on windows and reopening solved it for me.

What u did basically? Just closed the minimised application from the taskbar?

**Comment by Nosh118** [comment]
Yup, that’s all I did.

**Comment by Adil-MohammedK** [comment]
> Just to let anyone know who doesn’t want to compile themselves, I’m from the UK and had this error and closing it from the taskbar on windows and reopening solved it for me.

Can you explain it better? I tried it and it didn't work.

**Comment by Adil-MohammedK** [comment]
Did what s mentioned in this issue. Now working
https://github.com/cryptofyre/Apple-Music-Electron/issues/88

**Comment by Lvieira21** [comment]
I'm from brazil, and even after disabling CORS, it shows that is not available in my country.

**Comment by shivkar2n** [comment]
I'm from India. I'm also getting the same error.

**Comment by kir84** [comment]
I'm from Russia and i have too this bug on 2.3.0. And i get a trouble then build app - " not found folder or file /var/tmp/pamac-build-kir_84/apple-music-electron/scr/assets/icon.png". I just put this folder and file in place but i thing this is uncorrect.

**Comment by child-duckling** [comment]
@kir84 
> apple-music-electron/scr/assets/icon.png". I just put this folder and file in place but i thing this is uncorrect.
the correct placement of icon.png is in `apple-music-electron/src/assets/icon.png`
---------------------------------------------------------------^^^ This, instead of `scr` which you put it in
All you need to do is rename the `scr` folder to `src` and you should be all set!



As for the `Apple Music is not supported in your country/region`, this is an ongoing issue that we are trying to fix or at LEAST bandaid until a fix comes out from Apple.

**Comment by mysteriously** [comment]
I see this screen when I am trying to open settings. However I know that settings does not open app settings, but Apple account settings.

**Comment by child-duckling** [comment]
This is fixed in the upcoming [v2.4.0 release ](https://github.com/cryptofyre/Apple-Music-Electron/releases/tag/v2.4.0-beta2)

**Comment by RebellionBritney** [comment]
> This is fixed in the upcoming [v2.4.0 release ](https://github.com/cryptofyre/Apple-Music-Electron/releases/tag/v2.4.0-beta2)

Really hope so, it's still not working on the beta version

**Comment by coredev-uk** [comment]
Is AuthMode not working?

**Comment by RebellionBritney** [comment]
> Is AuthMode not working?

Guess so, I still can't log in

**Comment by coredev-uk** [comment]
Are you turning it on in the config?

**Comment by RebellionBritney** [comment]
> Are you turning it on in the config?

Yeah, I forgot to quit the app before try it again, it's working now. Thank you.

**Comment by child-duckling** [comment]
please refer to #155 for updated instructions
