### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Disablio** [cryptofyre/Apple-Music-Electron#99]
I'm sorry Im new to this and I just downloaded it but I don't know how to turn on dark mode and it doesn't affect what I do with my windows settings. Thanks!

**Comment by coredev-uk** [comment]
By default the application should chose your windows theme, if it fails to do so you can force the theme in the config.

**Comment by Disablio** [comment]
Can you please tell me how to where to find how? I'm new to this.

**Comment by coredev-uk** [comment]
Well, on the current main build you can only edit the configuration file and then recompile, in the upcoming build you can edit the configuration file without having to recompile. You can find more information on compiling [here](https://github.com/cryptofyre/Apple-Music-Electron/wiki/Compiling-on-Platforms).

**Comment by Disablio** [comment]
Thank you
